config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entities
  resources :transactions
  resources :transaction_type
  resources :transac_categs
  resources :payee_customers
  resources :payee_customer_types, only: [:index, :new, :create, :edit, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :charts, only: [:index]

  root :to => 'welcome#index'

end

app/controllers/payee_customer_types_controller.rb
class PayeeCustomerTypesController < ApplicationController
  before_action :find_payee_customer_type, only: [:show, :edit, :update, :destroy]

  def index
    @payeeCustomerTypes = PayeeCustomerType.all.order(created_at: :desc)
  end

  def new
    @payeeCustomerType = PayeeCustomerType.new
  end

  def create
    @payeeCustomerType = PayeeCustomerType.new payee_customer_type_params

    if @payeeCustomerType.save

      redirect_to payee_customer_types_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @payeeCustomerType.update(payee_customer_type_params)
      redirect_to payee_customer_types_path, success: 'Item updated!'
    else
      render :edit
    end
  end

  def destroy
    @payeeCustomerType.destroy
    redirect_to payee_customer_types_path, success: 'Item deleted!'
  end

  private

  def payee_customer_type_params
    params.require(:payee_customer_type).permit(:title, :description)
  end

  def find_payee_customer_type
    if params[:id]
      @payeeCustomerType = PayeeCustomerType.find params[:id]
    end
  end
end

app/views/payee_customer_types/_form.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Payee/Customer Type Register</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= payee_customer_types_path %>">Index</a>
    </div>
  </div>

  <div class="container">
    <div class="col-lg-9">
    <%= form_for @payeeCustomerType, html: {class:'form-horizontal', id:'reg_form'} do |f| %>
      <fieldset>
        <!-- Form Name -->
      <legend> Payee / Customer Type Register </legend>
      <!-- Text input-->
      <div class="form-group">
        <div class="col-md-6  inputGroupContainer">
          <%= f.label :title %>
          <div class="input-group"></i></span>
            <%= f.text_field :title, id:'title', class: 'form-control', placeholder: 'Here goes the  title type' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6  inputGroupContainer">
          <%= f.label :description %>
          <div class="input-group"></i></span>
            <%= f.text_field :description, id:'description', class: 'form-control', placeholder: 'Here goes the description type' %>
          </div>
        </div>
      </div>
      <!-- Button -->
      <div class="form-group">
        <div class="col-md-4">
          <%= f.submit class: 'btn btn-warning' %>
        </div>
      </div>
    </fieldset>
    <% end %>
    </div>
  </div>
</div>

app/views/payee_customer_types/edit.html.erb
<%= render 'form' %>

app/views/payee_customer_types/index.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line space-between">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Payee / Customer Type List</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= new_payee_customer_type_path %>" >New Type</a>
    </div>
  </div>
  <div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Payee / Customer Type Table</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Description</th>
              <th>
                <i class="fa fa-cog"></i>
              </th>
            </tr>
          </thead>
          <% @payeeCustomerTypes.each do |payeeCustomerType| %>
            <tbody>
              <tr>
                <td><%= payeeCustomerType.id %></td>
                <td><%= payeeCustomerType.title %></td>
                <td><%= payeeCustomerType.description %></td>
                <th>
                  <%= link_to edit_payee_customer_type_path(payeeCustomerType) do %>
                    <i class="fa fa-fw fa-edit"></i> |
                  <% end %>
                  <%= link_to(payee_customer_type_path(payeeCustomerType),
                        method: :delete,
                        data: {confirm: 'Are you sure?'}
                      ) do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </th>
              </tr>
            </tbody>
          <% end %>
          <tfoot>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Description</th>
              <th></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
</div>

app/views/payee_customer_types/new.html.erb
<%= render 'form' %>