config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entities
  resources :transactions
  resources :transaction_type
  resources :transac_categs
  resources :payee_customers
  resources :payee_customer_types, only: [:index, :new, :create, :edit, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :charts, only: [:index]

  root :to => 'welcome#index'

end

app/controllers/transaction_type_controller.rb
class TransactionTypeController < ApplicationController
  before_action :find_transacType, only: [:show, :edit, :update, :destroy]

  def index
    @transacTypes = TransactionType.all.order(created_at: :desc)
  end

  def new
    @transacType = TransactionType.new
  end

  def create
    @transacType = TransactionType.new transacType_params

    if @transacType.save
      redirect_to transaction_type_index_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @transacType.update(transacType_params)
      redirect_to transaction_type_index_path, success: 'Item updated!'
    else
      render :edit
    end
  end

  def destroy
    @transacType.destroy
    redirect_to transaction_type_index_path, success: 'Item deleted!'
  end

  private

  def transacType_params
    params.require(:transaction_type).permit(
      :description
    )
  end

  def find_transacType
    if params[:id]
      @transacType = TransactionType.find params[:id]
    end
  end
end

app/views/transaction_type/_form.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Transaction Type Register</li>
    </ol>
    <div class="myBtnDiv">
      <a href="/transaction_type">Index</a>
    </div>
  </div>

  <div class="container">
    <div class="col-lg-9">
    <%= form_for @transacType, html: {class:'form-horizontal', id:'reg_form'} do |f| %>
    <% if @transacType.errors.present? %>
      <p>
      <%= @transacType.errors.full_messages.join(', ') %>
      </p>
    <% end %>
      <fieldset>
        <!-- Form Name -->
      <legend> Transaction Type Register </legend>
      <!-- Text input-->
      <div class="form-group">
        <div class="col-md-6  inputGroupContainer">
          <%= f.label :description %>
          <div class="input-group">
            <%= f.text_field :description, id:'description', class: 'form-control', placeholder: 'Here goes the type description' %>
          </div>
        </div>
      </div>
      <!-- Button -->
      <div class="form-group">
        <div class="col-md-4">
          <%= f.submit class: 'btn btn-warning' %>
        </div>
      </div>
    </fieldset>
    <% end %>
    </div>
  </div>

</div>

app/views/transaction_type/edit.html.erb
<%= render 'form' %>

app/views/transaction_type/index.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line space-between">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Transaction Type List</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= new_transaction_type_path %>" >New Type</a>
    </div>
  </div>
  <div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Transaction Type Table</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Description</th>
              <th>
                <i class="fa fa-cog"></i>
              </th>
            </tr>
          </thead>
          <% @transacTypes.each do |transacType| %>
            <tbody>
              <tr>
                <td><%= transacType.id %></td>
                <td><%= transacType.description %></td>
                <th>
                  <%= link_to edit_transaction_type_path(transacType) do %>
                    <i class="fa fa-fw fa-edit"></i> |
                  <% end %>
                  <%= link_to(transaction_type_path(transacType),
                        method: :delete,
                        data: {confirm: 'Are you sure?'}
                      ) do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </th>
              </tr>
            </tbody>
          <% end %>
          <tfoot>
            <tr>
              <th>Id</th>
              <th>Description</th>
              <th></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
</div>

app/views/transaction_type/new.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line">
    <ol class="breadcrumb float-left">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Form Transaction Type</li>
    </ol>
    <ol class="breadcrumb float-right">
      <li class="breadcrumb-item">
        <a href="/transaction_type">Index</a>
      </li>
    </ol>
  </div>

  <div class="container" style="clear: both;">
    <div class="col-lg-9">
    <br>

    <!-- <form class="form-horizontal" action=" " method="post"  id="reg_form"> -->
    <%= form_for @transacType, :url => {:action => 'create',
  :controller => 'transaction_type'}, class: 'form-horizontal', id: 'reg_form'  do |f| %>
      <fieldset>
        <!-- Form Name -->
      <legend> Transaction Type Register </legend>
      <!-- Text input-->
      <div class="form-group">
        <!-- <label class="col-md-4 control-label">Description</label> -->
        <div class="col-md-6  inputGroupContainer">
          <%= f.label :description %>
          <div class="input-group"></i></span>
            <%= f.text_field :description, class: 'form-control', placeholder: 'Here goes the type description' %>
            <!-- <input  name="description" placeholder="Description" class="form-control"  type="text"> -->
          </div>
        </div>
      </div>
          <!-- Button -->
          <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
              <!-- <button type="submit" class="btn btn-warning" >Send <span class="glyphicon glyphicon-send"></span></button> -->
              <%= f.submit 'submit', class: 'btn btn-warning' %><span class="glyphicon glyphicon-send"></span>
            </div>
          </div>
        </fieldset>
        <% end %>
      </form>
    </div>
  </div>
    <!-- /.container -->
    <script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>

    <script type="text/javascript">

       $(document).ready(function() {
        $('#reg_form').bootstrapValidator({
            // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                description: {
                    validators: {
                            stringLength: {
                            min: 4,
                        },
                            notEmpty: {
                            message: 'Please supply a description for the type of transaction'
                        }
                    }
                },
              }
            })
            .on('success.form.bv', function(e) {
                $('#success_message').slideDown({ opacity: "show" }, "slow") // Do something ...
                    $('#reg_form').data('bootstrapValidator').resetForm();

                // Prevent form submission
                e.preventDefault();

                // Get the form instance
                var $form = $(e.target);

                // Get the BootstrapValidator instance
                var bv = $form.data('bootstrapValidator');

                // Use Ajax to submit form data
                $.post($form.attr('action'), $form.serialize(), function(result) {
                    console.log(result);
                }, 'json');
            });
    });
 </script>
</div>