config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entities
  resources :transactions
  resources :transaction_type
  resources :transac_categs
  resources :payee_customers
  resources :payee_customer_types, only: [:index, :new, :create, :edit, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :charts, only: [:index]

  root :to => 'welcome#index'

end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
  has_many :transactions, dependent: :destroy
  validates :description, presence: true, length: {minimum: 2, maximum: 10}

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :find_transac

  def index
    @transacs = Transaction.all.order(created_at: :desc)

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "transaction_report",
        layout: "layouts/pdf",
        template: "transactions/index.html.erb",
        encoding: "UTF-8",
        # no_background: true,
        disposition: "inline"
      end
    end
  end

  def new
    @transac = Transaction.new
  end

  def create
    @transac = Transaction.new transac_params

    if @transac.save
      redirect_to transactions_path
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @transac.update(transac_params)
      redirect_to transactions_path, success: 'Transaction updated!'
    else
      render :edit
    end
  end

  def destroy
    @transac.destroy
    redirect_to transactions_path, success: 'Transaction deleted!'
  end

  private

  def transac_params
    params.require(:transaction).permit(
      :details,
      :date,
      :value,
      :transaction_type_id,
      :entity_id,
      :transac_categ_id,
      :payee_customer_id
    )
  end

  def find_transac
    if params[:id]
      @transac = Transaction.find params[:id]
    end
  end
end

app/views/transactions/_form.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Transaction Register</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= transactions_path %>">Index</a>
    </div>
  </div>

  <div class="container">
    <div class="col-lg-12">
    <%= form_for @transac, html: {class:'form-horizontal', id:'reg_form'} do |f| %>
    <% if @transac.errors.present? %>
      <p>
      <%= @transac.errors.full_messages.join(', ') %>
      </p>
    <% end %>

      <fieldset>
        <!-- Form Name -->
      <legend> Transaction Registration </legend>
      <!-- Text input-->
      <div class="form-group">
        <div class="form-row">
          <div class="col-md-12  inputGroupContainer">
            <%= f.label :details %>
            <div class="input-group">
              <%= f.text_field :details, class: 'form-control', placeholder: 'Here goes the details' %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="form-row">
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :date %>
            <div class="input-group">
              <%#= f.date_select :date, {}, id:'date', class: 'form-control', placeholder: 'Here goes the date' %>
              <%= f.text_field :date, id:'date', class: 'form-control', placeholder: 'Here goes the date' %>
            </div>
          </div>
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :value %>
            <div class="input-group">
              <%= f.text_field :value, id:'value', class: 'form-control', placeholder: 'Here goes the value' %>
            </div>
          </div>
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :transaction_type %>
            <div class="input-group">
              <% transacTypes = TransactionType.all.map { |transacType| [transacType.description, transacType.id] } %>
              <%= f.select :transaction_type_id, options_for_select(transacTypes), {}, {class: 'custom-select', placeholder: 'Here goes the transaction type'} %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="form-row">
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :transac_categ, value: 'Category'%>
            <div class="input-group">
              <% transacCats = TransacCateg.all.map { |transacCat| [transacCat.title, transacCat.id] } %>
              <%= f.select :transac_categ_id, options_for_select(transacCats), {}, {class: 'custom-select', placeholder: 'Here goes the transaction category'} %>
            </div>
          </div>
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :entity %>
            <div class="input-group">
              <% entities = Entity.all.map { |entitie| [entitie.name, entitie.id] } %>
              <%= f.select :entity_id, options_for_select(entities), {}, {class: 'custom-select', placeholder: 'Here goes the entity', multiple: false} %>
            </div>
          </div>
          <div class="col-md-4  inputGroupContainer">
            <%= f.label :payee_customer, value: 'Payee/Customer'%>
            <div class="input-group">
              <% payeeCusts = PayeeCustomer.all.map { |payeeCust| [payeeCust.name, payeeCust.id] } %>
              <%= f.select :payee_customer_id, options_for_select(payeeCusts), {}, {class: 'custom-select', placeholder: 'Here goes the transaction category'} %>
            </div>
          </div>
        </div>
      </div>
      <!-- Button -->
      <div class="form-group">
        <div class="col-md-4">
          <%= f.submit class: 'btn btn-warning' %>
        </div>
      </div>
    </fieldset>
    <% end %>
    </div>
  </div>
</div>

app/views/transactions/edit.html.erb
<%= render 'form' %>

app/views/transactions/index.html.erb
<div class="container-fluid">
  <div class="calendar"></div>

  <!-- Breadcrumbs-->
  <div class="same-line space-between">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Transactions List</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= new_transaction_path %>" >New Transaction</a>
    </div>
  </div>
  <div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Transactions Table</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Category</th>
              <th>Details</th>
              <th>Value</th>
              <th>
                <i class="fa fa-cog"></i>
              </th>
            </tr>
          </thead>
          <% total = 0 %>
          <% @transacs.each do |transac| %>
            <tbody>
              <tr>
                <td><%= link_to transac.date, transaction_path(transac) %></td>
                <td><%= link_to transac.transaction_type.description, transaction_path(transac) %></td>
                <td><%= link_to transac.transac_categ.title, transaction_path(transac) %></td>
                <td><%= link_to transac.details, transaction_path(transac) %></td>
                <td><%= link_to number_to_currency(transac.value), transaction_path(transac) %></td>
                <td>
                  <%= link_to edit_transaction_path(transac) do %>
                    <i class="fa fa-fw fa-edit"></i> |
                  <% end %>
                  <%= link_to(transaction_path(transac),
                        method: :delete,
                        data: {confirm: 'Are you sure?'}
                      ) do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            </tbody>
            <% total = total + transac.value %>
          <% end %>
          <tfoot>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th style="align-text= right">Total: </th>
              <th><%= number_to_currency(total) %></th>
              <th></th>
            </tr>
          </tfoot>
        </table>
        <%= link_to 'Create PDF document', transactions_path(@transacs, format: "pdf") %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= line_chart Transaction.group(:date).sum(:value), discrete: true %>
      </div>
      <div class="col-6">
        <%= bar_chart Transaction.group(:date).sum(:value) %>
      </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
</div>

app/views/transactions/index_c.html.erb
<div id="calendar"></div>

app/views/transactions/new.html.erb
<%= render 'form' %>

app/views/transactions/show.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <div class="same-line">
    <ol class="breadcrumb first">
      <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Show Entity</li>
    </ol>
    <div class="myBtnDiv">
      <a href="<%= entities_path %>">Index</a>
    </div>
  </div>

    <div class="container">
      <div class="card card-register mx-auto">
        <div class="card-header">Entity</div>
        <div class="card-body">

      <h4><%= @entity.name %></h4>

      <table class="table">
        <tr>
          <td scope="row">Doc Number:</td>
          <td scope="row"><%= @entity.docNumber %></td>
        </tr>
        <tr>
          <td scope="row">Address:</td>
          <td scope="row"><%= @entity.address%></td>
        </tr>
        <tr>
          <td scope="row">Postal Code:</td>
          <td scope="row"><%= @entity.postaCode%></td>
        </tr>
        <tr>
          <td scope="row">E-mail:</td>
          <td scope="row"><%= @entity.email%></td>
        </tr>
        <tr>
          <td scope="row">Phone:</td>
          <td scope="row"><%= @entity.phone%></td>
        </tr>
      </table>

      <p><%= link_to '< Edit >', edit_entity_path(@entity) %></p>
    </div>
  </div>
</div>