config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entities
  resources :transactions
  resources :transaction_type
  resources :transac_categs
  resources :payee_customers
  resources :payee_customer_types, only: [:index, :new, :create, :edit, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :charts, only: [:index]

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Final Project about CodeCore Bootcamp - Cohort 21 (Nov 2017)">
    <meta name="author" content="Wellington Cunha">

    <title>Financial Management App - Fmapp</title>
    <%= csrf_meta_tags %>

    <!-- Page level plugin CSS-->
    <!-- <link href="assets/dataTables.bootstrap4.css" rel="stylesheet"> -->
    <!-- Custom styles for this template-->
    <!-- <link href="assets/sb-admin.css" rel="stylesheet"> -->
    <!-- Custom styles for register forms -->
    <!-- <link href="assets/form-validation.css" rel="stylesheet"> -->

    <!-- <link href="assets/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/style.css" rel="stylesheet" type="text/css" /> -->


    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/">
        <i class="fa fa-fw fa-sign-out"></i>
        <span class="nav-link-text">Fimnapp</span>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <% if user_signed_in? %>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
              <i class="fa fa-fw fa-file"></i>
              <span class="nav-link-text">Pages</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseExamplePages">
              <li>
                <a href="<%= transactions_path %>">Transactions</a>
              </li>
              <li>
                <a href="<%= entities_path %>">Entities</a>
              </li>
              <li>
                <a href="<%= payee_customers_path %>">Payees/Customers</a>
              </li>
              <li>
                <a href="/transaction_type">Transaction types</a>
              </li>
              <li>
                <a href="<%= payee_customer_types_path %>">Payee/Customer types</a>
              </li>
              <li>
                <a href="<%= transac_categs_path %>">Transactions Categories</a>
              </li>
            </ul>
          </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
              <i class="fa fa-fw fa-wrench"></i>
              <span class="nav-link-text">Data Maintanance</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseComponents">
              <li>
                <a href="<%= new_transaction_path %>">New Transaction</a>
              </li>
              <li>
                <a href="<%= new_payee_customer_type_path %>">New Payee/Customer Type</a>
              </li>
              <li>
                <a href="<%= new_entity_path %>">New Entity</a>
              </li>
              <li>
                <a href="<%= new_payee_customer_path %>">New Payee/Customer</a>
              </li>
              <li>
                <a href="<%= new_transac_categ_path %>">New Transaction Category</a>
              </li>
              <li>
                <a href="<%= new_transaction_type_path %>">New Transaction Type</a>
              </li>
            </ul>
          </li>
          <% end %>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
            <a class="nav-link" href="/">
              <i class="fa fa-fw fa-dashboard"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
            <a class="nav-link" href="<%= charts_path %>">
              <i class="fa fa-fw fa-area-chart"></i>
              <span class="nav-link-text">Charts</span>
            </a>
          </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="TypeTransac">
            <a class="nav-link" href="<%= transactions_path %>">
              <i class="fa fa-fw fa-table"></i>
              <span class="nav-link-text">Table</span>
            </a>
          </li>
        <% end %>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
            <a class="nav-link" href="https://github.com/wdcunha/fmapp">
              <i class="fa fa-fw fa-link"></i>
              <span class="nav-link-text">Link</span>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
              <span class="d-lg-none">User
                <span class="badge badge-pill badge-primary">12 New</span>
              </span>
              <span class="indicator text-primary d-none d-lg-block">
                <i class="fa fa-fw fa-circle"></i>
              </span>
            </a>
            <div class="dropdown-menu" aria-labelledby="messagesDropdown">
              <% if user_signed_in? %>
                <h6 class="dropdown-header">Hi <%= current_user.first_name %>!</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= user_path(current_user.id) %>">
                  <strong>My Account</strong>
                  <div class="dropdown-message small">See and manage your profile</div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" data-toggle="modal" data-target="#exampleModal">
                  <strong>Logout</strong>
                  <div class="dropdown-message small">Finish your session</div>
                </a>

              <% else %>
                <h6 class="dropdown-header"><%= link_to 'Sign in', new_session_path %></h6>
              <% end %>
          </li>
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0 mr-lg-2">
              <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for...">
                <span class="input-group-append">
                  <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                  </button>
                </span>
              </div>
            </form>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_session_path %>">
                <i class="fa fa-fw fa-sign-in"></i>Login</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="content-wrapper">
      
      <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% elsif flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>


        <%= yield %>

        <footer class="sticky-footer">
          <div class="container">
            <div class="text-center">
              <small>Final Project © CodeCore Bootcamp 2017/2018</small>
            </div>
          </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
          <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
              <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <%= link_to("Logout", session_path, method: :delete, class:'btn btn-primary') %>
              </div>
            </div>
          </div>
        </div>
        <script src="assets/sb-admin.min.js"></script>
      </div>
      <!-- /.content-wrapper-->
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
<meta charset="utf-8" />
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  <%= wicked_pdf_javascript_include_tag "chartjs" %>

</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>